[programs.localnet]
mysolanaap = "6wwNtucDDkME38cjKyYC5EANpWVRmUKKf5s9PwjWHbo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/hakidehari/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
